# Exercise

# Use iris Dataset from sklearn liberary and use cross_val_score against the followeing models to measure the performance of each.
# In the end figure out the model with best performance

# 1-Logistic Regression
# 2-SVM
# 3-Random Forest

In [1]:
from sklearn.datasets import load_iris
from sklearn.model_selection import cross_val_score
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
import numpy as np

In [3]:
iris = load_iris()

# Logistic Regression

In [4]:
Lo = LogisticRegression()

In [8]:
l_score = cross_val_score(LogisticRegression(), iris.data, iris.target)
l_score

C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


array([0.96666667, 1.        , 0.93333333, 0.96666667, 1.        ])

In [9]:
np.mean(l_score)

np.float64(0.9733333333333334)

# Decision Tree

In [10]:
d_score = cross_val_score(DecisionTreeClassifier(), iris.data, iris.target)
d_score

array([0.96666667, 0.96666667, 0.9       , 0.96666667, 1.        ])

In [11]:
np.mean(d_score)

np.float64(0.9600000000000002)

# Support Vector Machine (SVM)

In [12]:
s_score = cross_val_score(SVC(), iris.data, iris.target)
s_score

array([0.96666667, 0.96666667, 0.96666667, 0.93333333, 1.        ])

In [13]:
np.mean(s_score)

np.float64(0.9666666666666666)

# Random Forest

In [14]:
rf_score=cross_val_score(RandomForestClassifier(), iris.data, iris.target)
np.mean(rf_score)

np.float64(0.96)