In [1]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier

In [3]:
import matplotlib.pyplot as plt
import pandas as pd

In [4]:
from sklearn.datasets import load_digits
digits = load_digits()

In [6]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(digits.data, digits.target, test_size=0.3)

In [45]:
le = LogisticRegression(max_iter=10000)
le.fit(X_train, y_train)
le.score(X_test, y_test)

0.9611111111111111

In [42]:
svm = SVC(max_iter=10000)
svm.fit(X_train, y_train)
svm.score(X_test, y_test)

0.9962962962962963

In [47]:
re = RandomForestClassifier()
re.fit(X_train, y_train)
re.score(X_test, y_test)

0.975925925925926

In [23]:
from sklearn.model_selection import KFold
kf = KFold(n_splits=3)
kf

KFold(n_splits=3, random_state=None, shuffle=False)

In [24]:
for train_index, test_index in kf.split([1,2,3,4,5,6,7,8,9]):
    print(train_index, test_index)

[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


In [25]:
def get_score(model, X_train, X_test, y_train, y_test):
    model.fit(X_train, y_train)
    return model.score(X_test, y_test)

In [26]:
get_score(LogisticRegression(), X_train, X_test, y_train, y_test)

C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.9629629629629629

In [27]:
from sklearn.model_selection import cross_val_score

In [33]:
cross_val_score(LogisticRegression(), digits.data, digits.target, cv=7)

C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stab

array([0.91439689, 0.94552529, 0.87548638, 0.93774319, 0.94163424,
       0.9375    , 0.90625   ])

In [32]:
cross_val_score(RandomForestClassifier(), digits.data, digits.target, cv=7)

array([0.93774319, 0.96108949, 0.86770428, 0.95719844, 0.97276265,
       0.9453125 , 0.9296875 ])

In [31]:
cross_val_score(SVC(), digits.data, digits.target, cv=7)

array([0.95719844, 0.96498054, 0.96498054, 0.98054475, 0.9922179 ,
       0.98046875, 0.92578125])

In [36]:
import numpy as np

In [48]:
scores1 = cross_val_score(LogisticRegression(), digits.data, digits.target, cv=10)
np.mean(scores1)

C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stab

np.float64(0.928193668528864)

In [39]:
scores2 = cross_val_score(RandomForestClassifier(n_estimators=15), digits.data, digits.target, cv=10)
np.mean(scores2)

np.float64(0.9365797641216634)

In [53]:
scores2 = cross_val_score(RandomForestClassifier(n_estimators=50), digits.data, digits.target, cv=10)
np.mean(scores2)

np.float64(0.9549286157666046)

# Based on above we can say that we required 50 trees for fair estimation as it perform better than other digits

In [54]:
scores3 = cross_val_score(SVC(), digits.data, digits.target, cv=10)
np.mean(scores3)

np.float64(0.9699503414028554)