In [16]:
import numpy as np
import pandas as pd
from sklearn import linear_model
from sklearn.linear_model import LinearRegression

In [2]:
df=pd.read_csv('homprices.csv')
df

area  bedroom  age   price
0  2500      3.0   20  550000
1  3000      4.0   15  565000
2  3200      NaN   18  610000
3  3600      3.0   30  597000
4  4000      5.0    8  760000

In [3]:
import math

In [4]:
median_bedroom=math.floor(df.bedroom.median())

In [5]:
df.bedroom=df.bedroom.fillna(median_bedroom)
df

area  bedroom  age   price
0  2500      3.0   20  550000
1  3000      4.0   15  565000
2  3200      3.0   18  610000
3  3600      3.0   30  597000
4  4000      5.0    8  760000

In [17]:
# reg=linear_model.LinearRegression
reg = LinearRegression()

In [7]:
df

area  bedroom  age   price
0  2500      3.0   20  550000
1  3000      4.0   15  565000
2  3200      3.0   18  610000
3  3600      3.0   30  597000
4  4000      5.0    8  760000

In [14]:
print(df.isna().sum())

area       0
bedroom    0
age        0
price      0
dtype: int64


In [8]:
df[['area', 'bedroom', 'age', 'price']] = df[['area', 'bedroom', 'age', 'price']].apply(pd.to_numeric)

In [9]:
print(df[['area', 'bedroom', 'age']].shape)

(5, 3)


In [10]:
print(df['price'].shape)

(5,)


In [12]:
print(df[['area', 'bedroom', 'age']].isnull().sum())

area       0
bedroom    0
age        0
dtype: int64


In [13]:
print(df['price'].isnull().sum())

0


In [18]:
# reg.fit(df[['area', 'bedroom', 'age']], df['price'])
reg.fit(df[['area', 'bedroom', 'age']], df['price'])


LinearRegression()

In [19]:
reg.coef_

array([   124.06017505, -20037.03501094,  -6295.13129103])

In [20]:
reg.intercept_

np.float64(398668.5448577679)

In [25]:
reg.predict([[2500, 3, 20]])

C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([522805.25164114])

# linear equation

In [27]:
reg.coef_

array([   124.06017505, -20037.03501094,  -6295.13129103])

In [28]:
reg.intercept_

np.float64(398668.5448577679)

In [ ]:
price=m1x1+m2x2+m3x3+b

In [29]:
124.06017505*2500+-20037.03501094*3+-6295.13129103*20+398668.5448577679

522805.2516293479

In [32]:
reg.predict([[3000, 3, 40]])

C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([458932.71334792])

In [33]:
reg.predict([[2500, 4, 5]])

C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([597195.18599562])

# Exercise

In [36]:
import numpy as np
import pandas as pd
from sklearn.linear_model import LinearRegression
from word2number import w2n

In [38]:
df=pd.read_csv('hiring_record.csv')
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0        NaN                    8.0                           9      50000
1        NaN                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    NaN                           7      72000
7     eleven                    7.0                           8      80000

# Handling Na values

In [39]:
df.experience=df.experience.fillna('zero')

In [40]:
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0       zero                    8.0                           9      50000
1       zero                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    NaN                           7      72000
7     eleven                    7.0                           8      80000

In [41]:
df.experience=df.experience.apply(w2n.word_to_num)

In [42]:
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0           0                    8.0                           9      50000
1           0                    8.0                           6      45000
2           5                    6.0                           7      60000
3           2                   10.0                          10      65000
4           7                    9.0                           6      70000
5           3                    7.0                          10      62000
6          10                    NaN                           7      72000
7          11                    7.0                           8      80000

In [46]:
import math
median_test_score=math.floor(df['test_score(out of 10)'].median())
median_test_score

8

In [49]:
df['test_score(out of 10)']=df['test_score(out of 10)'].fillna(median_test_score)

In [50]:
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0           0                    8.0                           9      50000
1           0                    8.0                           6      45000
2           5                    6.0                           7      60000
3           2                   10.0                          10      65000
4           7                    9.0                           6      70000
5           3                    7.0                          10      62000
6          10                    8.0                           7      72000
7          11                    7.0                           8      80000

In [51]:
reg=LinearRegression()

In [53]:
reg.fit(df[['experience', 'test_score(out of 10)', 'interview_score(out of 10)']], df['salary($)'])

LinearRegression()

In [56]:
float(reg.predict([[7, 17, 7]]))

C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\Users\User\AppData\Local\Temp\ipykernel_1052\1268891042.py:1: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  float(reg.predict([[7, 17, 7]]))


84241.63027656477

In [58]:
float(reg.predict([[7, 20, 10]]))

C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\Users\User\AppData\Local\Temp\ipykernel_1052\1034512260.py:1: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  float(reg.predict([[7, 20, 10]]))


96394.46870451237

In [61]:
float(reg.predict([[10, 17, 7]]))

C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\Users\User\AppData\Local\Temp\ipykernel_1052\3149987794.py:1: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  float(reg.predict([[10, 17, 7]]))


92680.49490538574